apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: simple-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"