apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      - name: spring-boot-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
